JOIN AND SPLIT FUNCTIONS

CREATE A NUMPY ARRAYS AND JOIN THEM BOTH HORIZONTALLY AND VERTICALLY (BOTH 2-D AND 3-D)

In [7]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [15]:
array1=np.array([[2,3,4],[5,6,7]])
print(array1)

[[2 3 4]
 [5 6 7]]


In [21]:
array2=np.array([[2,1,1],[5,5,7]])
print(array2)

[[2 1 1]
 [5 5 7]]


HORIZONTAL JOIN

In [25]:
hjoin=np.hstack((array1,array2))
print(hjoin)

[[2 3 4 2 1 1]
 [5 6 7 5 5 7]]


VERTICAL JOIN

In [35]:
vjoin=np.vstack((array1,array2))
print(vjoin)

[[2 3 4]
 [5 6 7]
 [2 1 1]
 [5 5 7]]


3 DIMENSIONAL

In [29]:
array4=np.array([[[1,2,3],[3,4,5]],[[3,4,3],[2,1,1]]])
print(array4)

[[[1 2 3]
  [3 4 5]]

 [[3 4 3]
  [2 1 1]]]


In [31]:
array5=np.array([[[3,2,3],[8,4,9]],[[4,4,1],[3,8,1]]])
print(array5)

[[[3 2 3]
  [8 4 9]]

 [[4 4 1]
  [3 8 1]]]


VERTICAL JOIN

In [33]:
vjoin=np.vstack((array4,array5))
print(vjoin)

[[[1 2 3]
  [3 4 5]]

 [[3 4 3]
  [2 1 1]]

 [[3 2 3]
  [8 4 9]]

 [[4 4 1]
  [3 8 1]]]


HORIZONTAL JOIN

In [41]:
hjoin=np.hstack((array4,array5))
print(hjoin)

[[[1 2 3]
  [3 4 5]
  [3 2 3]
  [8 4 9]]

 [[3 4 3]
  [2 1 1]
  [4 4 1]
  [3 8 1]]]
